### PR TITLE
applySchema can return a new DDF or modify it inplace

### PR DESCRIPTION
**Pull request by Huandao0812**
### Description and related tickets, documents
fix SchemaHandler line separator

Reviewers: @zkidkid 

### How to test
Describe how this PR is tested. In case manual testing is required, describe how to do so.

### PR Progress
Make sure all checkboxes below are checked before merged
- [ ] Branch is in format `prefix/description` (see [this](http://www.guyroutledge.co.uk/blog/git-branch-naming-conventions/))
- [ ] Merge check has no conflicts. PR checks passed.
- [x] Code review is done.

### CODE REVIEW

**Comment by Huandao0812** [comment]
@zkidkid you used the wrong file separator in your IDE, please make sure it is \"n"

**Comment by zkidkid** [comment]
@hai-adatao please take note that Huan has added inPlace flag in this ApplySchema function, so we will remove it in PE. (because currently PE process mutate not DDF).

**Comment by Huandao0812** [comment]
@hai-adatao @zkidkid the flag in PE api will be there, I just move the logic to DDF

**Comment by hai-adatao** [comment]
@zkidkid this PR has no UT, why merge this?

**Comment by Huandao0812** [comment]
@zkidkid can you help add UT for this please

**Pull request merged**
