### PR TITLE
Mean added

### PR DESCRIPTION
**Pull request by ljzzju**
add the mean method in R and fix some docs

### CODE REVIEW

**Comment by ctn** [comment]
Seems like a good idea to me. Merge?

**Comment by khangich** [comment]
ok to test

**Comment by hunggpham** [comment]
Are you guys hiring?    I applied to Data Scientist position but noone
replied.

**Comment by khangich** [comment]
ok to test

**Comment by khangich** [comment]
ok to test

**Comment by khangich** [comment]
ok to test

**Comment by ctn** [comment]
I'm going to merge this if there are no objections @khangich @nhanitvn

**Comment by adatao-ddf** [comment]
Ok to me.

Touched, not typed. Please excuse brevity and typos.

**Pull request merged**
