### PR TITLE
typo: grpup --> group

### PR DESCRIPTION
**Pull request by Tarrasch**

### CODE REVIEW

**Comment by khangich** [comment]
ok to test

**Comment by dabaitu** [comment]
Can one of the admins verify this patch?

**Comment by Tarrasch** [comment]
Verify o_O? `.html` is a markup language and not turing complete. :)

**Comment by binhmop** [comment]
@Tarrasch those are auto-messages from Jenkins, we'll remove it :-) Thanks for the edit!

**Comment by Tarrasch** [comment]
Haha, I thought they seemed inhumanly fast to reply ^^

**Pull request merged**
