### PR TITLE
add some fixes

### PR DESCRIPTION
**Pull request by nhanitvn**
1. to make the R package build-able
2. add db_list_tables and db_has_table for DDFManager
To-do: tbl does not work complaining that there is no db_list_tables for DDFManager class though that function works when it is called in a standalone way.

### CODE REVIEW

**Comment by ctn** [comment]
Is this PR to be updated, or closed?

**Comment by mbbui** [comment]
Too old to merge.

**Comment by ctn** [comment]
@nhanitvn sup?

**Comment by nhanitvn** [comment]
Let's close this. the dplyr code is not mature yet.

**Pull request closed without merging**
