### PR TITLE
Revert "Merge pull request #123 from ddf-project/revert-121-ddfSpark"

### PR DESCRIPTION
**Pull request by Huandao0812**
This reverts commit 4371e274fb08d5bd005be5b2bdc0093286d37569, reversing
changes made to d1bf1ad34558a8f3b50f17d66a0f9297911f2db2.

### CODE REVIEW

**Comment by khangich** [comment]
ok to test

**Comment by Huandao0812** [comment]
ok to test

**Comment by Huandao0812** [comment]
retest this please

**Comment by mbbui** [comment]
retest this please

**Pull request merged**
