### PR TITLE
add default implementation for IGloballyAddressable

### PR DESCRIPTION
**Pull request by Huandao0812**
### Description and related tickets, documents

Reviewers: @phvu @hai-adatao 

### Breaking changes & backward compatible issues
Is this PR a breaking change or has backward compatible issue (e.g: changes in API names, interfaces, signature / remove something...)?
If yes, please state out what and tag, and if it can possibly affect BA, please tag aht, tuananh, khangpham and baonguyen

### How to test
Describe how this PR is tested. In case manual testing is required, describe how to do so.

### PR Progress
Make sure all checkboxes below are checked before merged
- [ ] Branch is in format `prefix/description` (see [this](http://www.guyroutledge.co.uk/blog/git-branch-naming-conventions/))
- [ ] Merge check has no conflicts. PR checks passed.
- [ ] Code review is done.

### CODE REVIEW

**Comment by phvu** [comment]
I feel this will increase the complexity of the inheritance hierarchy (if we are gonna make other classes inherit `GloballyAddressable`). Maybe we should add those new functions into `AGloballyAddressable` instead?

I think one "cleaner" way is to use default methods (http://www.programcreek.com/2014/12/default-methods-in-java-8-and-multiple-inheritance/) to implement `getGlobalObjectType` and `getUri` directly in `IGloballyAddressable`, and other things like UUID, name and namespace will be handled in `AGloballyAddressable`.

**Comment by Huandao0812** [comment]
@phvu fixed

**Comment by phvu** [comment]
lgtm

**Comment by PangZhi** [comment]
@Huandao0812  lgtm

**Pull request merged**
