### PR TITLE
[PE-1169] Python shell

### PR DESCRIPTION
**Pull request by phvu**
This partly resolves PE-1169. It covers most of DDF basic functions (according to this list: https://github.com/ddf-project/DDF/blob/master/R/package/NAMESPACE). ML-related functions will be handled in a separated PR.

All ML functions in R are also ported. No more PR.

Please help review @nhanitvn @jing

### CODE REVIEW

**Comment by nhanitvn** [comment]
:+1: @phvu

**Comment by PangZhi** [comment]
thanks @phvu. How can i run the test? 
When i run python test_ddf.py, i get the error:     
from ddf import DDFManager, DDF_HOME
ImportError: No module named ddf

Can you add it in readme?

**Comment by phvu** [comment]
@PangZhi it's written here: https://github.com/ddf-project/DDF/tree/master/python#2-run-tests

**Comment by PangZhi** [comment]
@phvu i followed the guide, still get this error.

**Comment by phvu** [comment]
@PangZhi can you paste the actual commands you used? And the output of `ls` and `pwd`?

**Comment by phvu** [comment]
@PangZhi can you help test if `examples/flink.py` works? I don't have flink, thanks.

TODO:
[] missing DDF functions: subset, aggregate

**Comment by hai-adatao** [comment]
Test fails, it seems master branch is unstable itself, can someone help take a look? @PangZhi

**Comment by PangZhi** [comment]
@hai-adatao The only error i can find in the log is about 
[ERROR] SLF4J: Class path contains multiple SLF4J bindings.
This sounds deployment for me. I will check it.

**Comment by PangZhi** [comment]
This error is due to test setting. Merge now.

**Pull request merged**
