### PR TITLE
Fix/python shell

### PR DESCRIPTION
**Pull request by PangZhi**
This PR is to sync python shell and R shell with updated sql api of ddf.

/cc @hai-adatao @phvu @nhanitvn

### CODE REVIEW

**Comment by phvu** [comment]
lgtm

**Comment by hai-adatao** [comment]
lgtm

**Comment by nhanitvn** [comment]
@PangZhi Could we set a default value (either True or False) for queryOnDDF param?

**Comment by nhanitvn** [comment]
lgtm

**Pull request merged**
