### PR TITLE
update sql parser for function support

### PR DESCRIPTION
**Pull request by PangZhi**
This PR is to update SQL support for Function, and it fixes the following query:
SELECT id,if(loan_status like "%Late%" or loan_status like "%Charged%" or loan_status " +
            "like "%Default%" or loan_status like "%Grace%", 1, 0) as risk,risk_category FROM {1}

/cc @hai-adatao @Huandao0812 @nhanitvn

### CODE REVIEW

**Comment by adatao-ddf** [comment]
Which Jira ticket does it fix? @jing

**Comment by PangZhi** [comment]
I didn't include jira here because I think it's better not to include company jira info in open-source project.

**Comment by adatao-ddf** [comment]
Ah, right. Thanks.

**Comment by Huandao0812** [comment]
@PangZhi you shouldn't change the pom.xml in core and spark folder, it'll be generated from Rootbuild.scala

**Comment by hai-adatao** [comment]
@Huandao0812 we didn't exclude pom.xml file in .gitignore, did we? The rootbuild is at 1.4.8 now so I suppose this change is ok

**Pull request merged**
