### PR TITLE
clean sql api, replace datasource param as a boolean

### PR DESCRIPTION
**Pull request by PangZhi**
This PR is to change the sql api.
The confusing datasource param is replaced with a boolean value queryOnDDF.

/cc @nhanitvn @hai-adatao @Huandao0812

### CODE REVIEW

**Comment by hai-adatao** [comment]
@lebinh can you help take a look?

**Comment by lebinh** [comment]
@PangZhi this does clear up some confusion in our SQL api but I believe the different between (1) query on DDF and (2) query on the data source are big enough to warrant 2 different APIs instead of just a parameter.

**Comment by PangZhi** [comment]
@lebinh I suggest keep this first. Because new apis need more changes and we can refactor it later. Currently the open source version and the product version are diverged.

**Comment by lebinh** [comment]
@PangZhi agree then, we just need to keep that in mind when refactoring DDFManager.

**Pull request merged**
