### PR TITLE
do not allow new column with same name as an existing one

### PR DESCRIPTION
**Pull request by dabaitu**
@mbbui @nhanitvn please review

### CODE REVIEW

**Comment by mbbui** [comment]
Tom, you need to merge with master again.

**Comment by mbbui** [comment]
Test failed

**Comment by dabaitu** [comment]
@mbbui you mean merge with head of ddf-sparksql-adatao?

**Comment by Huandao0812** [comment]
retest this please

**Comment by dabaitu** [comment]
retest this please

**Comment by dabaitu** [comment]
@mbbui @Huandao0812 unit tests fixed. This should have the correct behaviors.

**Pull request merged**
